//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftKnacksProject.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime DateRegister { get; set; }
        public Nullable<bool> ConfirmMail { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
