//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftKnacksProject.Api.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Wishes = new HashSet<Wish>();
            this.Gifts = new HashSet<Gift>();
        }
    
        public long Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime DateRegister { get; set; }
        public bool ConfirmMail { get; set; }
        public string EmailStamp { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual ICollection<Wish> Wishes { get; set; }
        public virtual ICollection<Gift> Gifts { get; set; }
    }
}
